### ISSUE TITLE
Serialize double nested object into post form data?

### ISSUE THREAD

**Issue by mdedetrich** [mdedetrich/stripe-scala#1]
According to the documentation at https://stripe.com/docs/api#create_customer, the source input (which itself is a dictionary) contains another possible dictionary which is metadata.

How does one serialize a double nested object into post form parameters? Relevant code is here https://github.com/mdedetrich/stripe-scala/blob/master/src/main/scala/org/mdedetrich/stripe/v1/Customers.scala#L266-L286

**Comment by leonardehrenfried** [comment]
This has been solved a while ago with the `PostParams` utility functions.
