### ISSUE TITLE
Change from play-json to a better JSON client

### ISSUE THREAD

**Issue by mdedetrich** [mdedetrich/stripe-scala#15]
Currently I have a preference for using Circe rather than play-json, here are my current pros/cons

Pros
- Has macros to support a lot of use cases, including automatic `Encoder`/`Decoder` transformations for a generic case class `T` that translates to lower case
- Uses a HistoryOP to provide very granular error messages
- Cross compiled for Scalajs (might make sense to move the basic models of stripe to a cross compiled scala.js project at some point in the future for client side support of stripe.js with Scala.js?)
- Not bounded to any framework apart from Cats and quite independent which means it updates according to Scala versions much better (i.e. it had Scala 2.12 support much sooner than play-json did). Also receives updates a lot more frequently than play-json does

Cons
- Depends on Cats, which is a pretty big dependency. Not sure if shading the Cats dependency is realistic, but I am wary of introducing big dependencies to ease friction for end users (in any case, I was planning to shade play-json as well)

@leonardehrenfried  Thoughts?

**Comment by leonardehrenfried** [comment]
I admit that I have a bit of an emotional attachment to play-json having used it for years so I'm not totally objective. I'd just like to point out that play-json has been moved into a separate repository recently: https://github.com/playframework/play-json

It is going to be released separately from the main play project.

What really is annoying is having to define the `Format` implementation because Stripe uses lowercase. However I recently discovered this tiny library which could help us in this respect: https://github.com/tototoshi/play-json-naming

I'd be willing to try out a new JSON framework though but the cats dependency is a little heavy for my liking. I've read that you need a compiler plugin for the automatic case class derivation. Do you need the plugin only for compiling the lib or also when you want to use it?

**Comment by leonardehrenfried** [comment]
Also, I just found out that you can use camel case in play-json in the next release: https://github.com/playframework/playframework/commit/ed819049709b1c4622f1585a3c2731a94346d25a

**Comment by mdedetrich** [comment]
After using circe extensively at work I am leaning towards moving to circe. Firstly to answer your questions

>  I've read that you need a compiler plugin for the automatic case class derivation. 

We won't be using this, we would have to name all of our classes to snake case (since thats how it works). It would also add a big amount to compile time. Circe does actually have an ability to automatically change from camelCase to lowerCase. However what I typically use is `forProduct` variants, it still has boilerplate in having to define the fields but its much less then what we currently have now and it doesn't add a lot to compile times (we also don't have to add the compiler plugin), an example would be

Right now we have something like this
```scala
  implicit val discountReads: Reads[Discount] = (
    (__ \ "coupon").read[Coupon] ~
      (__ \ "customer").read[String] ~
      (__ \ "end").read[OffsetDateTime](stripeDateTimeReads) ~
      (__ \ "start").read[OffsetDateTime](stripeDateTimeReads) ~
      (__ \ "subscription").readNullable[String]
  ).tupled.map((Discount.apply _).tupled)

  implicit val discountWrites: Writes[Discount] = Writes(
    (discount: Discount) =>
      Json.obj(
        "object"       -> "discount",
        "coupon"       -> discount.coupon,
        "customer"     -> discount.customer,
        "end"          -> Json.toJson(discount.end)(stripeDateTimeWrites),
        "start"        -> Json.toJson(discount.start)(stripeDateTimeWrites),
        "subscription" -> discount.subscription
    ))
```

The equivalent in Circe (using forProduct) would be 
```scala
implicit val discountDecoder: Decoder[Discount] = Decoder.forProduct5(
  "coupon",
  "customer",
  "end",
  "start",
  "subscription"
)(Discount.apply)

implicit val discountEncoder: Encoder[Discount] = Encoder.forProduct6(
  "object",
  "coupon",
  "customer",
  "end",
  "start",
  "subscription"
)(x => ("discount", x.coupon, x.customer, x.end, x.start, x.subscription))
```

As you can see its much cleaner. I am also not the biggest fan of automatic camel case -> snake case (and vice versa) derivation because there are usually enough exceptions in JSON models that its not really worth it

The only remaining issue is Cats. Its true that its a pretty big dependency (although it may be possible to shade), however Cats does add stuff that I would see being useful in other ways (i.e. adding right biased map/flatMap on `Either` which is missing in Scala 2.11). Thankfully unlike Scalaz, cats is designed to be as minimal as possible as a dependency and circe only depends on cats core
