### ISSUE TITLE
ChargeInput only accepts CreditCard and not token

### ISSUE THREAD

**Issue by andrewsim** [mdedetrich/stripe-scala#35]
```
case class ChargeInput(
    ...
    source: Option[SourceInput.Card] = None,
    ...
)
```
Does this mean that the `source` must be a credit card? Are there any way to pass in a token instead?

**Comment by leonardehrenfried** [comment]
You can also set the customer field. That is if you have customers.

But it seems that the type should be changed to just `SourceInput`. I never really used that field so I  it's not as comprehensive as it could be.

We are very open for pull requests though and would guide you through the process.

**Comment by leonardehrenfried** [comment]
Actually, I just implemented this myself. Please watch the pull request for any updates.

**Comment by leonardehrenfried** [comment]
Version 0.2.3 with a fix for this has been released.
